apiVersion: apps/v1
kind: Deployment
metadata:
    name: sampledevopsapplication
    labels:
        app: nagp-devops
spec:
    replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
            app: nagp-devops
    template:
        metadata:
            labels:
                app: nagp-devops
        spec:
            containers:
            - name: nagp-devops-helm
              image: {{ .Values.image }}
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nagp-devops-service
spec:
    type: NodePort
    selector:
        app: nagp-devops
    ports:
    - name: port8080
      protocol: TCP
      nodePort: {{ .Values.nodeport }}
      port: 8080
      targetPort: 8080